n_workers: ${local_env.n_workers}
data_dir: ${paths.data_dir}
output_dir: ${paths.preprocessed_dir}

cqt_hparams:
  down_sampling_rate: 22050
  normalize_wave: true
  stft_type: "cqt"
  bins_per_octave: 24
  total_n_bins: 192
  hop_length: 256
  db_scale: false
  normalize_cqt: false

split_unit_in_bars: 4 # cut tracks into n bar long segment (l_excerpt)
split_hop_bar_len: 1 # hop length when sliding the window (l_overlap)