# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  name: "tset_n_${datamodule.test_player_n}" # name of the run
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "seq2seq_Guitar_Transcription"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  # entity: "" # set to name of your wandb team
  group: ""
  tags: [] #["${datamodule.test_player_n}"]
  job_type: "tset_n_${datamodule.test_player_n}"
