# Generates a summary of all layers in a LightningModule with rich text formatting.
model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2 # the maximum depth of layer nesting that the summary will include
