_target_: src.datamodules.guitarset.GuitarsetDataModule
data_dir: ${paths.data_dir}
train_val_split_ratio: 0.9
test_player_n: 5
batch_size: 16
normalize_cqt: False # "z_score" or "frequency"
cache_dataset: False
num_workers: ${local_env.n_workers}
dataloader_workers: ${local_env.n_workers}
pin_memory: False
persistent_workers: False
preprocess_on_training_start: True